### ISSUE TITLE
Failed to start Server

### ISSUE THREAD

**Issue by ImOlli** [Hermsi1337/docker-ark-server#10]
When i try to run the docker container i always end up with this error message in my logs:

```Running command 'run' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
2021-06-03 09:52:09: start
2021-06-03 09:52:09: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?SessionName=\"Ark\"\?ServerPassword=\"arkistcool\"\?ServerAdminPassword=\"administcool\"\?MaxPlayers=20\?GameModIds\?GameModIds\?RCONEnabled=True\?listen -log -log
/usr/local/bin/arkmanager: line 1289: /app/server/ShooterGame/Binaries/Linux/ShooterGameServer: No such file or directory
2021-06-03 09:52:09: Server PID: 135
2021-06-03 09:52:14: Bad PID ''; expected '135'
2021-06-03 09:52:14: exited with status 0```

**Comment by Hermsi1337** [comment]
Hmm could you share some more information about your setup? E.g. `docker-compose.yml`, etc.

It'd be also great if you could attach logs with env `DEBUG=true` set.

Thanks! (=

**Comment by msdos621** [comment]
I am seeing the same issue :(

This is my docker-compose
```
version: '3'

volumes:
  ark-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/srv/ark/data"

services:
  server:
    restart: always
    container_name: ark_server
    image: hermsi/ark-server:latest
    volumes:
      - ark-data:/app
    environment:
      - SESSION_NAME=${SESSION_NAME}
      - SERVER_MAP=${SERVER_MAP}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - UPDATE_ON_START=${UPDATE_ON_START}
      - BACKUP_ON_STOP=${BACKUP_ON_STOP}
      - PRE_UPDATE_BACKUP=${PRE_UPDATE_BACKUP}
      - WARN_ON_STOP=${WARN_ON_STOP}
    ports:
      # Port for connections from ARK game client
      - "7777:7777/udp"
      # Raw UDP socket port (always Game client port +1)
      - "7778:7778/udp"
      # RCON management port
      - "27020:27020/tcp"
      # Steam's server-list port
      - "27015:27015/udp"
    networks:
      - default
```

This is all the logging I am getting
```
root@ssh:/srv/ark# DEBUG=true docker-compose up -d
Creating network "ark_default" with the default driver
Creating ark_server ... done
root@ssh:/srv/ark# docker-compose logs -f -t
Attaching to ark_server
server_1  | 2021-06-07T23:01:48.595453092Z _______________________________________
server_1  | 2021-06-07T23:01:48.595841330Z
server_1  | 2021-06-07T23:01:48.596897639Z # Ark Server - Mon 07 Jun 2021 11:01:48 PM UTC
server_1  | 2021-06-07T23:01:48.596928337Z # UID 1000 - GID 1000
server_1  | 2021-06-07T23:01:48.596932254Z _______________________________________
server_1  | 2021-06-07T23:01:48.597485136Z Setting up folder and file structure...
server_1  | 2021-06-07T23:01:48.597847185Z No game files found. Installing...
server_1  | 2021-06-07T23:01:48.619148552Z Running command 'install' for instance 'main'
server_1  | 2021-06-07T23:02:07.687281633Z Installing ARK server ...  .....................................No crontab set
server_1  | 2021-06-07T23:02:07.715486463Z Running command 'run' for instance 'main'
server_1  | 2021-06-07T23:02:07.734861061Z 2021-06-07 23:02:07: start
server_1  | 2021-06-07T23:02:07.736813554Z 2021-06-07 23:02:07: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?SessionName=sessionname\?ServerPassword=something\?ServerAdminPassword=something\?MaxPlayers=15\?GameModIds\?GameModIds\?RCONEnabled=True\?listen -log -log
server_1  | 2021-06-07T23:02:07.737380011Z /usr/local/bin/arkmanager: line 1289: /app/server/ShooterGame/Binaries/Linux/ShooterGameServer: Permission denied
server_1  | 2021-06-07T23:02:07.738778050Z 2021-06-07 23:02:07: Server PID: 127
server_1  | 2021-06-07T23:02:12.745631668Z 2021-06-07 23:02:12: Bad PID ''; expected '127'
server_1  | 2021-06-07T23:02:12.748031271Z 2021-06-07 23:02:12: exited with status 0
```
