### ISSUE TITLE
SteamAPI_Init() failed; SteamAPI_IsSteamRunning() after configuring Steam login session?

### ISSUE THREAD

**Issue by KWall24** [Hermsi1337/docker-ark-server#108]
When starting the server, I get some errors relating to SteamAPI.

```
ark_server  | chown: warning: '.' should be ':': 'steam.'
ark_server  | chown: warning: '.' should be ':': 'steam.'**
ark_server  | Starting periodic command scheduler: cron.
ark_server  | _______________________________________
ark_server  | 
ark_server  | # Ark Server - Sun Jun  1 04:32:33 UTC 2025
ark_server  | # IMAGE_VERSION: '1736226124'
ark_server  | # RUNNING AS USER 'steam' - '1000'
ark_server  | # ARGS: --arkopt,-NoBattlEye 
ark_server  | _______________________________________
ark_server  | Setting up folder and file structure...
ark_server  | $UPDATE_ON_START is 'true'...
ark_server  | Running command 'update' for instance 'main'
ark_server  | Checking for update; PID: 47
ark_server  | Your server is already up to date! The most recent version is .
ark_server  | Running command 'run' for instance 'main'
ark_server  | 2025-06-01 04:32:35: start
ark_server  | 2025-06-01 04:32:35: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?SessionName=Tasha\'s\ Tea\?ServerPassword=TashasTea\?ServerAdminPassword=SpecialK3018\!\?MaxPlayers=6\?GameModIds\?GameModIds\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=27020\?listen -log -NoBattlEye -log
ark_server  | 2025-06-01 04:32:35: Server PID: 152
ark_server  | [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.**
ark_server  | Setting breakpad minidump AppID = 346110
```
Initially I ignored them, but I figured I should try to [configure the steam login session](https://github.com/Hermsi1337/docker-ark-server?tab=readme-ov-file#configure-steam-login-session). It seems okay, but there's a config error right off the bat that I'm not sure if it's a problem or not.

```
kwall24@debian:/docker/ark-server$ sudo mkdir Steam
kwall24@debian:/docker/ark-server$ sudo chown 1000:1000 Steam
kwall24@debian:/docker/ark-server$ sudo docker run --rm --entrypoint /home/steam/steamcmd/steamcmd.sh -it -u steam -v $(pwd)/Steam:/home/steam/Steam hermsi/ark-server '+login **user1** "**pass1**"'
WARNING: Error loading config file: /root/.docker/config.json: : read /root/.docker/config.json: is a directory
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Downloading update (0 of 52,312 KB)...
[  0%] Downloading update (1,163 of 52,312 KB)...
[  2%] Downloading update (4,602 of 52,312 KB)...
[  8%] Downloading update (7,700 of 52,312 KB)...
[ 14%] Downloading update (9,711 of 52,312 KB)...
[ 18%] Downloading update (11,974 of 52,312 KB)...
[ 22%] Downloading update (13,729 of 52,312 KB)...
[ 26%] Downloading update (15,687 of 52,312 KB)...
[ 29%] Downloading update (17,538 of 52,312 KB)...
[ 33%] Downloading update (19,352 of 52,312 KB)...
[ 36%] Downloading update (21,304 of 52,312 KB)...
[ 40%] Downloading update (23,048 of 52,312 KB)...
[ 44%] Downloading update (24,952 of 52,312 KB)...
[ 47%] Downloading update (26,856 of 52,312 KB)...
[ 51%] Downloading update (28,680 of 52,312 KB)...
[ 54%] Downloading update (30,376 of 52,312 KB)...
[ 58%] Downloading update (32,136 of 52,312 KB)...
[ 61%] Downloading update (34,184 of 52,312 KB)...
[ 65%] Downloading update (35,912 of 52,312 KB)...
[ 68%] Downloading update (37,560 of 52,312 KB)...
[ 71%] Downloading update (39,480 of 52,312 KB)...
[ 75%] Downloading update (41,256 of 52,312 KB)...
[ 78%] Downloading update (43,224 of 52,312 KB)...
[ 82%] Downloading update (45,000 of 52,312 KB)...
[ 86%] Downloading update (46,760 of 52,312 KB)...
[ 89%] Downloading update (48,024 of 52,312 KB)...
[ 91%] Downloading update (48,712 of 52,312 KB)...
[ 93%] Downloading update (49,624 of 52,312 KB)...
[ 94%] Downloading update (50,606 of 52,312 KB)...
[ 96%] Downloading update (51,510 of 52,312 KB)...
[ 98%] Downloading update (52,312 of 52,312 KB)...
[100%] Downloading update (52,312 of 52,312 KB)...
[100%] Download complete.
[----] Installing update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
UpdateUI: skip show logosteamcmd.sh[1]: Restarting steamcmd by request...
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logo
Steam Console Client (c) Valve Corporation - version 1747702063
-- type 'quit' to exit --
Loading Steam API...IPC function call IClientUtils::GetConnectedUniverse took too long: 51 msec
OK
Logging in using username/password.
Logging in user '**user1**' [U:1:0] to Steam Public...This account is protected by a Steam Guard mobile authenticator.
Please confirm the login in the Steam Mobile app on your phone.

Waiting for confirmation...OK
Waiting for client config...OK
Waiting for user info...OK

Steam>exit
Unloading Steam API...OK

```

After doing that, I've updated my docker compose as here.

```
services:
  ark_server:
    restart: always
    container_name: ark_server
    image: hermsi/ark-server:latest
    volumes:
      - /docker/ark-server/server:/app
      - /docker/ark-server/backups:/home/steam/ARK-Backups
      - /docker/ark-server/Steam:/home/steam/Steam:rw
    environment:
      SESSION_NAME: ...
      SERVER_MAP: ....
      SERVER_PASSWORD: ...
      ADMIN_PASSWORD: ...
      MAX_PLAYERS: 6
      UPDATE_ON_START: true
      BACKUP_ON_STOP: true
      PRE_UPDATE_BACKUP: true
      WARN_ON_STOP: true
      DISABLE_BATTLEYE: true
      STEAM_LOGIN: **user1**
    ports:
      - 7777:7777/udp
      - 7778:7778/udp
      - 27020:27020/tcp
      - 27015:27015/udp
```
But I'm still getting `ark_server  | [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.` when (re)starting the container. 

Is this expected? I've looked through other issues here and I see similar questions but I'm not really seeing an answer.
