### ISSUE TITLE
Local Docker Build is Failing

### ISSUE THREAD

**Issue by ThePowershellNinja** [Hermsi1337/docker-ark-server#28]
I have been trying to perform a local build of the docker image for awhile now and I have been failing. I just realized that the build is stopping when trying to perform this command:
![image](https://user-images.githubusercontent.com/6169890/147832122-d70539f1-219a-4e2d-b62b-7ab163b8c508.png)

The same command does not fail outside of my docker build, which tells me that the link is still good and there is something wrong with the docker file? Does any one have any pointers? I set up the environment exactly as the GitLab pipeline is set up for. Has anyone else experienced this?

PS: I am doing all of this so that I can test some fixes that I want to make, and my first logical choice is to make sure that I can build the image at all.

**Comment by ThePowershellNinja** [comment]
Oh, now that I post it, I realize that it nullifying the ${ARK_TOOLS_VERSION} variable... and it occurs to me that I didn't set up the environment this morning when I started at it again... xD

**Comment by ThePowershellNinja** [comment]
Alright, it looks like it is trying to go now.

The quotes around /app is concerning. I'm not sure if it's just the echo that is quoting is weird or if it is actually putting quotes in the directory itself:
![image](https://user-images.githubusercontent.com/6169890/147832864-452c38d2-1e77-4828-bc68-32aa06744db9.png)

For reference, this is my docker-compose file that I'm using to test for the time being:
``` yaml
version: '3'

services:
  server:
    restart: always
    container_name: ark_micahtest
    image: micahtest:latest
    volumes:
      - /opt/data/ark/micahtest:/app
      - /opt/data/ark/micahtest/backups:/home/steam/ARK-Backups
    environment:
      - SESSION_NAME="JustToClayrify.net - MicahTest"
      - SERVER_MAP="CrystalIsle"
      - SERVER_PASSWORD=""
      - ADMIN_PASSWORD="MyPassword"
      - MAX_PLAYERS="70"
      - UPDATE_ON_START=true
      - BACKUP_ON_STOP=true
      - PRE_UPDATE_BACKUP=true
      - WARN_ON_STOP=${WARN_ON_STOP}
      - ARK_SERVER_VOLUME="/app"
      - GAME_CLIENT_PORT=8777
      - UDP_SOCKET_PORT=8778
      - RCON_PORT=37020
      - SERVER_LIST_PORT=37015
      - GAME_MOD_IDS="731604991,1609138312,1400323349,1342813568,1315534671,793605978,816908578"
    ports:
      # Port for connections from ARK game client
      - "8777:8777/udp"
      # Raw UDP socket port (always Game client port +1)
      - "8778:8778/udp"
      # RCON management port
      - "37020:37020/tcp"
      # Steam's server-list port
      - "37015:37015/udp"
    networks:
      - default
```
