### ISSUE TITLE
Game download does not start

### ISSUE THREAD

**Issue by Melethainiel** [Hermsi1337/docker-ark-server#52]
I tried to set up a server with the following docker-compose file :
```yml
version: '3'

services:
  server:
    restart: always
    container_name: ark_server
    image: hermsi/ark-server:latest
    volumes:
      - /home/administrator/ark/ark-server:/app
      - /home/administrator/ark/ark-server-backups:/home/steam/ARK-Backups
    environment:
      - SESSION_NAME=Docker Ark
      - SERVER_MAP=TheIsland
      - SERVER_PASSWORD=pass
      - ADMIN_PASSWORD=pass_2
      - MAX_PLAYERS=10
      - UPDATE_ON_START=1
      - BACKUP_ON_STOP=1
      - PRE_UPDATE_BACKUP=1
      - WARN_ON_STOP=1
    ports:
      # Port for connections from ARK game client
      - "7777:7777/udp"
      # Raw UDP socket port (always Game client port +1)
      - "7778:7778/udp"
      # RCON management port
      - "27020:27020/tcp"
      # Steam's server-list port
      - "27015:27015/udp"
    networks:
      - default
```

but in the logs it stops at the line `"@NoPromptForPassword" = "1"` like below :

```log
Installing ARK serverExecuting /home/steam/steamcmd/steamcmd.sh +@NoPromptForPassword 1 +force_install_dir /app/server +login anonymous +app_update 376030 validate +quit
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1654574676
-- type 'quit' to exit --
Loading Steam API...OK
"@NoPromptForPassword" = "1"
```

Any idea ?
