### ISSUE TITLE
environment variables are not respected

### ISSUE THREAD

**Issue by Behoston** [Hermsi1337/docker-ark-server#55]
```yml
behoston@bmc:~/ark$ cat docker-compose.yml 
version: '3'

services:
  server:
    restart: always
    container_name: ark_server
    image: hermsi/ark-server:latest
    volumes:
      - ./ark-server:/app
      - ./ark-server-backups:/home/steam/ARK-Backups
    environment:
      - SESSION_NAME="Grańsko w ARK"
      - SERVER_MAP=TheIsland
      - SERVER_PASSWORD=*****
      - ADMIN_PASSWORD=*****
      - MAX_PLAYERS=10
      - UPDATE_ON_START=true
      - BACKUP_ON_STOP=true
      - PRE_UPDATE_BACKUP=true
      - WARN_ON_STOP=true
```
Server status
```behoston@bmc:~/ark$ docker exec ark_server arkmanager status
Running command 'status' for instance 'main'
 Server running:   Yes 
 Server PID:   248 
 Server listening:   Yes 
Server Name: ARK #878753 - (v346.14)
Steam Players: 0 / 70
Active Steam Players: 0
 Server online:   Yes 
 ARKServers link:   http://arkservers.net/server/79.184.5.36:27015 
 Steam connect link:   steam://connect/79.184.5.36:27015 
 Server build ID:   8946738 
```

Clean run, I removed all files but docker-compose.yml, removed container then run docker-compose up. As you can see max players still 70 and players are able to join without password.
