### ISSUE TITLE
restart container will cause Game.ini be reset

### ISSUE THREAD

**Issue by xxxsen** [Hermsi1337/docker-ark-server#56]
i change some properties in Game.ini file, but it will be reset to empty file when container restart.

stop container->modify file->restart container => file be reset
modify file when container already start->restart container => file be reset

how can i save it?

**Comment by xxxsen** [comment]
![image](https://user-images.githubusercontent.com/3880276/174491279-4992873c-71e2-48f0-8a9f-525e93f87f1c.png)

seems all files in this folder will be recreate when server restart..

**Comment by xxxsen** [comment]
here is my docker-compose file

```yml
version: '3'

services:
  server:
    restart: always
    container_name: ark_server
    image: hermsi/ark-server:latest
    volumes:
      - /data/docker/ark/ark-server:/app
      - /data/docker/ark/ark-server-backups:/home/steam/ARK-Backups
    environment:
      - SESSION_NAME=abcdefg
      - SERVER_MAP=TheIsland
      - SERVER_PASSWORD=hello
      - ADMIN_PASSWORD=test123
      - MAX_PLAYERS=32
      - UPDATE_ON_START=true
      - BACKUP_ON_STOP=false
      - PRE_UPDATE_BACKUP=true
      - WARN_ON_STOP=true
      - GAME_MOD_IDS="2024410037,1204667931,1496720667,1931415003,1928871727,1705579268,1211297684,569786012,1267677473,845855498,731604991,889745138,1404697612,566885854,924933745,2790994538,2799135883,2804332920,2811002545"
    ports:
      # Port for connections from ARK game client
      - "7777:7777/udp"
      # Raw UDP socket port (always Game client port +1)
      - "7778:7778/udp"
      # RCON management port
      - "27020:27020/tcp"
      # Steam's server-list port
      - "27015:27015/udp"
    networks:
      - default

```
