### ISSUE TITLE
first mod id in GAME_MOD_IDS always install fail

### ISSUE THREAD

**Issue by xxxsen** [Hermsi1337/docker-ark-server#60]
id: 1204667931 is a valid id, the first picture shows that the id is listed normally, but installed failed.
In the second picture, I added an invalid id: 0 in front of this id, and then redeployed the server, and the installation was successful at this time.

GAME_MOD_IDS="0,1204667931,1496720667,1931415003,1928871727,1705579268,1211297684,569786012,1267677473,845855498,731604991,889745138,1404697612,566885854,924933745,2790994538,2799135883,2804332920,2811002545,2786238883,1373744537"

![image](https://user-images.githubusercontent.com/3880276/176007679-a5a97e12-2efe-45ef-af18-b47303dc20ba.png)
![image](https://user-images.githubusercontent.com/3880276/176007776-4b4370ad-20aa-4184-94ed-410d89433a29.png)

**Comment by Hermsi1337** [comment]
Hey @xxxsen,

somehow I can not reproduce this issue.

I've published a major refactoring of this image today. Could you try using this image? `quay.io/hermsi1337/ark-server:refactor`

Could you also attach a startup-log with `DEBUG=true` if

**Comment by Hermsi1337** [comment]
This should be fixed by #57 ... try using the current `latest`-img.

Feel free to open if you have any issues (= 


Regards

**Comment by xxxsen** [comment]
> This should be fixed by #57 ... try using the current `latest`-img.
> 
> Feel free to open if you have any issues (=
> 
> Regards

problem still exists with the new version of the image

**Comment by xxxsen** [comment]
> Hey @xxxsen,
> 
> somehow I can not reproduce this issue.
> 
> I've published a major refactoring of this image today. Could you try using this image? `quay.io/hermsi1337/ark-server:refactor`
> 
> Could you also attach a startup-log with `DEBUG=true` if it does not work with the new image?

i cant pull it down

**Comment by Hermsi1337** [comment]
`refactor` is now `latest`.

Could you share your `docker-compose.yml` as well as startup-logs with `DEBUG=true` ?

**Comment by xxxsen** [comment]
https://pastebin.com/8PMRc7Mw

here is my startup log

**Comment by xxxsen** [comment]
my docker-compose.yml

```yml
version: '3'

services:
  server:
    restart: always
    container_name: ark_server
      #image: quay.io/hermsi1337/ark-server:refactor
    image: hermsi/ark-server:latest
    volumes:
      - /data/docker/ark/ark-server:/app
      - /data/docker/ark/ark-server-backups:/home/steam/ARK-Backups
    environment:
      - DEBUG=true
      - SESSION_NAME=test_svr
      - SERVER_MAP=TheIsland
      - SERVER_PASSWORD=test_pwd
      - ADMIN_PASSWORD=test_pwd_pwd
      - MAX_PLAYERS=32
      - UPDATE_ON_START=true
      - BACKUP_ON_STOP=false
      - PRE_UPDATE_BACKUP=true
      - WARN_ON_STOP=true
      - GAME_MOD_IDS="2003934830,1204667931,1496720667,1931415003,1928871727,1705579268,1211297684,569786012,1267677473,845855498,731604991,889745138,1404697612,566885854,924933745,2790994538,2799135883,2804332920,2811002545,2786238883,2824091110,751991809,2820647244,622595587,561820195"
    ports:
      # Port for connections from ARK game client
      - "7777:7777/udp"
      # Raw UDP socket port (always Game client port +1)
      - "7778:7778/udp"
      # RCON management port
      - "27020:27020/tcp"
      # Steam's server-list port
      - "27018:27015/udp"
    networks:
      - default
```
