### ISSUE TITLE
documentation on how to pass along additional server options.

### ISSUE THREAD

**Issue by woeisme** [Hermsi1337/docker-ark-server#66]
There seems to be very little documentation on where and syntax for passing along additional server configuration options using docker-compose.yml

I'd like clarification on where and how to properly specify options such as 
>UseVivox
>exclusivejoin 

Where should this occur? in the docker-compose.yml or GameUserSettings.ini or Game.ini  or arkmanager.cfg ?

**Comment by Hermsi1337** [comment]
Hey, you're right.. I will add docs for additional args later.

Your desired options have to be added to the `run`-command of `arkmanager`.  
In order to do so, you can use the `args`-key in `docker-compose.yml`:

```yaml
  args:
    - --arkopt,exclusivejoin
    - --arkopt,UseVivox
```

See here for references:

* https://github.com/arkmanager/ark-server-tools#common-options
* https://docs.docker.com/compose/compose-file/compose-file-v3/#args

**Comment by woeisme** [comment]
ah okay this is super useful information to know, perhaps a few additional docker-compose.yml examples added to the repo might be the best way to inform people for now without having to add tons of documentation.

As I'm still learning Docker and docker-compose does the args: value need to be preceeded by 
```build:
  context: .
  args:```

like in the docker documentation? Adding them after the 

>enviroment:

Just generates an error 

"ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.server: 'args'"

**Comment by Hermsi1337** [comment]
Sorry, I've attached the wrong documentation-ref. What I mean is `command`: https://docs.docker.com/compose/compose-file/compose-file-v3/#command

Like this:


```yaml
version: '3'

services:
  server:
    restart: always
    container_name: ark_server
    image: hermsi/ark-server:latest
    command: --arkopt,exclusivejoin --arkopt,UseVivox
    volumes:
      - ${HOME}/ark-server:/app
      - ${HOME}/ark-server-backups:/home/steam/ARK-Backups
    environment:
      - SESSION_NAME=${SESSION_NAME}
      - SERVER_MAP=${SERVER_MAP}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - UPDATE_ON_START=${UPDATE_ON_START}
      - BACKUP_ON_STOP=${BACKUP_ON_STOP}
      - PRE_UPDATE_BACKUP=${PRE_UPDATE_BACKUP}
      - WARN_ON_STOP=${WARN_ON_STOP}
    ports:
      # Port for connections from ARK game client
      - "7777:7777/udp"
      # Raw UDP socket port (always Game client port +1)
      - "7778:7778/udp"
      # RCON management port
      - "27020:27020/tcp"
      # Steam's server-list port
      - "27015:27015/udp"
    networks:
      - default
```
