### ISSUE TITLE
Some environment properties in docker-compose file not working

### ISSUE THREAD

**Issue by goliafrsigma** [Hermsi1337/docker-ark-server#68]
I want to change `TZ` in my server, but env property in docker-compose not working.
I know it has't in wiki, but how can i change time zone?
`DISABLE_BATTLEYE` not working, server still starts with battleye enabled.
Judging by the logs of the arkmanager `UPDATE_ON_START`, `PRE_UPDATE_BACKUP`, `BACKUP_ON_STOP` does't work to.

Maybe `"true"` parameter is wrong syntax?

```
version: "3.9"
services:
  ark:
    image: hermsi/ark-server:latest
    container_name: ark
    restart: always
    volumes:
      - $HOME/games/ark:/app
    environment:
      - SESSION_NAME=***
      - SERVER_MAP=TheIsland
      - SERVER_PASSWORD=***
      - ADMIN_PASSWORD=***
      - MAX_PLAYERS=2
      - UPDATE_ON_START="true"
      - BACKUP_ON_STOP="true"
      - PRE_UPDATE_BACKUP="true"
      - WARN_ON_STOP="true"
      - DISABLE_BATTLEYE="true"
      - TZ="Europe/Moscow"
    ports:
      - 7777:7777/tcp
      - 7777:7777/udp
      - 7778:7778/tcp
      - 7778:7778/udp
      - 27015:27015/tcp
      - 27015:27015/udp
      - 27020:27020/tcp
      - 27020:27020/udp
```

**Comment by Hermsi1337** [comment]
Hey @goliafrsigma, you must not use `"` around your environment-variables when using the `.yml`-array syntaxt.

If you do use `"` that way, they will get appended to the variable inside the container. And instead of `true` you have `"true"`. Which won't work (as you noticed).

Either do:

```yaml
environment:
  - UPDATE_ON_START=true
  - BACKUP_ON_STOP=true
  - PRE_UPDATE_BACKUP=true
```

Or:

```yaml
environment:
  UPDATE_ON_START: "true"
  BACKUP_ON_STOP: "true"
  PRE_UPDATE_BACKUP: "true"
```
