### ISSUE TITLE
Permission issue after adding Steam user

### ISSUE THREAD

**Issue by ecterun** [Hermsi1337/docker-ark-server#72]
I am getting an error after i add the steam user to the docker compose.

```
version: '3'

services:
  server:
    restart: always
    container_name: ark_server-02
    image: hermsi/ark-server:latest
    volumes:
      - /mnt/ark-data/ark-server:/app
      - /mnt/ark-data/ark-server-backups:/home/steam/ARK-Backups
      - /mnt/ark-data/Steam:/home/steam/Steam:rw
    environment:
      - SESSION_NAME=ServerName
      - SERVER_MAP=TheIsland
      - SERVER_PASSWORD=serverpass
      - ADMIN_PASSWORD=adminserverpass
      - MAX_PLAYERS=20
      - UPDATE_ON_START=false
      - BACKUP_ON_STOP=false
      - PRE_UPDATE_BACKUP=true
      - WARN_ON_STOP=true
      - STEAM_LOGIN=STEAMLOGIN
    ports:
      # Port for connections from ARK game client
      - "7777:7777/udp"
      # Raw UDP socket port (always Game client port +1)
      - "7778:7778/udp"
      # RCON management port
      - "27020:27020/tcp"
      # Steam's server-list port
      - "27015:27015/udp"
    networks:
      - default
```

Below is the error I am getting once I add the volume and steam login to the compose file.

```
ark_server-02 | # Ark Server - Sun Jul 24 21:38:57 UTC 2022
ark_server-02 | # IMAGE_VERSION: '1657602157'
ark_server-02 | # RUNNING AS USER 'steam' - '1000'
ark_server-02 | # ARGS:
ark_server-02 | _______________________________________
ark_server-02 | Setting up folder and file structure...
ark_server-02 | cp: failed to access '/app/arkmanager/arkmanager.cfg': Permission denied
ark_server-02 | Starting periodic command scheduler: cron.
ark_server-02 | _______________________________________
```
