### ISSUE TITLE
Running on ARM

### ISSUE THREAD

**Issue by rauldeheer** [Hermsi1337/docker-ark-server#78]
I'm trying to run this image on an ARM based system, but I get a startup error. I use the following `docker-compose` file:

```yml
version: '3'

services:
  server:
    restart: on-failure:2
    container_name: ark_server
    image: hermsi/ark-server:latest
    volumes:
      - ${HOME}/ark-server:/app
      - ${HOME}/ark-server-backups:/home/steam/ARK-Backups
    environment:
      - SESSION_NAME=${SESSION_NAME}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MAX_PLAYERS=4
    ports:
      - "7777:7777/udp"
      - "7778:7778/udp"
      - "27020:27020/tcp"
      - "27015:27015/udp"
    networks:
      - default
```

I get the following log when starting the stack:

```
      
Starting periodic command scheduler: cron.

_______________________________________


# Ark Server - Thu Sep  1 13:20:32 UTC 2022

# IMAGE_VERSION: '1661835742'

# RUNNING AS USER 'steam' - '1000'

# ARGS: 

_______________________________________

Setting up folder and file structure...

...successfully created /app/log

...successfully created /app/backup

...successfully created /app/staging

...successfully copied /conf.d/arkmanager.cfg to /app/arkmanager/arkmanager.cfg

...successfully copied /conf.d/arkmanager-user.cfg to /app/arkmanager/instances/main.cfg

...successfully copied /conf.d/crontab to /app/crontab

No game files found. Installing...

...successfully created /app/server/ShooterGame/Saved/SavedArks

...successfully created /app/server/ShooterGame/Content/Mods

...successfully created /app/server/ShooterGame/Binaries/Linux

Running command 'install' for instance 'main'

Installing ARK serverExecuting /home/steam/steamcmd/steamcmd.sh +@NoPromptForPassword 1 +force_install_dir /app/server +login anonymous +app_update 376030 validate +quit

/home/steam/steamcmd/steamcmd.sh: line 38: /home/steam/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error

Running command 'run' for instance 'main'

2022-09-01 13:20:33: start

2022-09-01 13:20:33: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?SessionName=ServerName\?ServerPassword=passwordserver\?ServerAdminPassword=passwordadmin\?MaxPlayers=4\?GameModIds\?GameModIds\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=27020\?listen -log -log

2022-09-01 13:20:33: Server PID: 262

2022-09-01 13:20:38: Bad PID ''; expected '262'
```
