### ISSUE TITLE
arkmanager throws Invalid steamcmd_user in config file

### ISSUE THREAD

**Issue by Mickroz** [Hermsi1337/docker-ark-server#79]
Hi,
im getting this when running status, i installed the docker container through a stack in portainer.

but console in ark server container says:
```
:/app# echo "${STEAM_USER}"
steam
```

my stack looks like:
```
ark-server:
    image: hermsi/ark-server:latest
    container_name: ark_server
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Amsterdam
      - SESSION_NAME=****
      - SERVER_MAP=TheIsland
      - SERVER_PASSWORD=****
      - ADMIN_PASSWORD=****
      - MAX_PLAYERS=10
      - UPDATE_ON_START=true
      - BACKUP_ON_STOP=true
      - GAME_MOD_IDS=123456
    ports:
      # Port for connections from ARK game client
      - "7777:7777/udp"
      # Raw UDP socket port (always Game client port +1)
      - "7778:7778/udp"
      # RCON management port
      - "27020:27020/tcp"
      # Steam's server-list port
      - "27015:27015/udp"
    volumes:
      - /home/mickroz/docker/ark-server:/app
      - /home/mickroz/docker/ark-server-backups:/home/steam/ARK-Backups
```
now im fairly new with docker, so i don't know where to look what might be wrong.
