### ISSUE TITLE
Can't access GameUserSettings.ini in WSL Mount

### ISSUE THREAD

**Issue by sneekee** [Hermsi1337/docker-ark-server#83]
So I've set up the server using this docker-compose file

```
version: '3'

volumes:
 ark_persistent_data:
 ark_persistent_data_backups:

services:
  server:
    restart: always
    container_name: ark_server
    image: hermsi/ark-server:latest
    volumes:
      -  ark_persistent_data:/app
      -  ark_persistent_data_backups:/home/steam/ARK-Backups
    environment:
      - SESSION_NAME=*****
      - SERVER_MAP=TheIsland
      - SERVER_PASSWORD=*****
      - ADMIN_PASSWORD=******
      - MAX_PLAYERS=10
      - WARN_ON_STOP=true
      - ENABLE_CROSSPLAY=true
      - DISABLE_BATTLEYE=true
      - UPDATE_ON_START=true
    ports:
      # Port for connections from ARK game client
      - "7777:7777/udp"
      # Raw UDP socket port (always Game client port +1)
      - "7778:7778/udp"
      # RCON management port
      - "27020:27020/tcp"
      # Steam's server-list port
      - "27015:27015/udp"
    networks:
      - default
```

However when I try to open GameUserSettings.ini under `\\wsl.localhost\docker-desktop-data\data\docker\volumes\arkserver_ark_persistent_data\_data` windows says it can't find the file specified. Any ideas what I'm doing wrong here?
