### ISSUE TITLE
Server didn't start caused by Thread failed to initialize

### ISSUE THREAD

**Issue by Hator21** [Hermsi1337/docker-ark-server#94]
Hi, 
ich habe versucht den Server wie in der Readme über docker-compse zu starte allerdings bekomme ich beim hochfahren folgenden Fehler: 
```
Starting ark_server ... done
Attaching to ark_server
ark_server | Starting periodic command scheduler: cron.
ark_server | _______________________________________
ark_server |
ark_server | # Ark Server - Mon Apr 24 06:40:07 UTC 2023
ark_server | # IMAGE_VERSION: '1681794104'
ark_server | # RUNNING AS USER 'steam' - '1000'
ark_server | # ARGS:
ark_server | _______________________________________
ark_server | Setting up folder and file structure...
ark_server | No game files found. Installing...
ark_server | Running command 'install' for instance 'main'
ark_server | Installing ARK serverExecuting /home/steam/steamcmd/steamcmd.sh +@NoPromptForPassword 1 +force_install_dir /app/server +login anonymous +app_update 376030 validate +quit
ark_server | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
ark_server | Looks like steam didn't shutdown cleanly, scheduling immediate update check
ark_server | src/tier0/threadtools.cpp (4139) : Probably deadlock or failure waiting for thread to initialize.
ark_server | [  0%] Checking for available updates...
ark_server | Thread failed to initialize
ark_server | src/tier0/threadtools.cpp (4139) : Probably deadlock or failure waiting for thread to initialize.
ark_server | Thread failed to initialize
```
docker-compose.yml
```
version: '3'

services:
  server:
    restart: always
    container_name: ark_server
    image: hermsi/ark-server:latest
    volumes:
      - /home/arkServer/ark-server:/app
      - /home/arkServer/ark-server-backups:/home/steam/ARK-Backups
    environment:
      - SESSION_NAME=test
      - SERVER_MAP=TheIsland
      - SERVER_PASSWORD=xxxxxx
      - ADMIN_PASSWORD=xxxxxx
      - MAX_PLAYERS=20
      - UPDATE_ON_START=true
      - BACKUP_ON_STOP=true
      - PRE_UPDATE_BACKUP=true
      - WARN_ON_STOP=true
    ports:
      # Port for connections from ARK game client
      - "7777:7777/udp"
      # Raw UDP socket port (always Game client port +1)
      - "7778:7778/udp"
      # RCON management port
      - "27020:27020/tcp"
      # Steam's server-list port
      - "27015:27015/udp"
    networks:
      - default

```
