### ISSUE TITLE
arkmanager not showing all informations

### ISSUE THREAD

**Issue by metal3z** [Hermsi1337/docker-ark-server#98]
instead of showing the following list of server information when running arkmanager status:
Running command 'status' for instance 'main'
 Server running:   Yes
 Server PID:   164
 Server listening:   Yes
Server Name: ARK-server
Steam Players: 0 / 20
Active Steam Players: 0
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/***REDACTED***:27015
 Steam connect link:   steam://connect/***REDACTED***:27015
 Server build ID:   8991126
 Server version:   346.16

i am getting only the following informations:
Running command 'status' for instance 'main'
 Server running:   Yes
 Server PID:   5874
 Server listening:   No
 Server build ID:   11617045
 Server version:   358.8

PS: the server is hosted in a GKE "google kubernetes cluster" in autopilot mode
deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ark
  name: ark
  namespace: ark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ark
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: ark
    spec:
      containers:
      - env:
        - name: DEBUG
          value: "true"
        - name: SERVER_MAP
          valueFrom:
            configMapKeyRef:
              key: server_map
              name: ark-config
        - name: SEVER_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: server_password
              name: ark-config
        - name: MAX_PLAYERS
          valueFrom:
            configMapKeyRef:
              key: max_players
              name: ark-config
        - name: SERVER_LIST_PORT
          valueFrom:
            configMapKeyRef:
              key: server_list_port
              name: ark-config
        - name: GAME_CLIENT_PORT
          valueFrom:
            configMapKeyRef:
              key: game_client_port
              name: ark-config
        - name: UPD_SOCKET_PORT
          valueFrom:
            configMapKeyRef:
              key: udp_socket_port
              name: ark-config
        - name: RCON_PORT
          valueFrom:
            configMapKeyRef:
              key: rcon_port
              name: ark-config
        - name: SESSION_NAME
          valueFrom:
            configMapKeyRef:
              key: session_name
              name: ark-config
        image: quay.io/hermsi1337/ark-server:latest-1689051741 #hermsi/ark-server:latest
        imagePullPolicy: Always
        name: ark-server
        resources:
          limits:
            cpu: 200m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 4000m
            ephemeral-storage: 1Gi
            memory: 4Gi
        ports:
        - containerPort: 27015
          protocol: UDP
        - containerPort: 27020
          protocol: TCP
        - containerPort: 7777
          protocol: UDP
        - containerPort: 7778
          protocol: UDP
        volumeMounts:
          - mountPath: /app/
            name: ark-app
      volumes:
        - name: ark-app
          persistentVolumeClaim:
            claimName: ark-pvc
```

configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ark-config
  namespace: ark
data:
  game_client_port: "7777"
  max_players: "15"
  rcon_port: "27020"
  server_list_port: "27015"
  server_map: TheIsland
  server_password: ********
  session_name: hello to ARK
  udp_socket_port: "7778"
```
